### ISSUE TITLE
An unbiased review.

### ISSUE THREAD

**Issue by theLMGN** [EclipseUK/Browser#5]
# **Look, before you ban me for who I am, i'm going to be as unbiased as possible in this quite critical review**

### Pros:
   - The logo looks nice I guess.

### Cons:
   - You can't resize the window
   - You can't maximise the window (the maximise button goes full screen)
   - [This.](https://theLMGN.likes-gay.men/3y0pg.jpg)
   - [What in gods name are these icons](https://theLMGN.likes-gay.men/asenb.png)
   - You know the FlatStyle property exists?
   - [At the top of the textbox theres a 4 pixel gap, and at the bottom there's only 2](https://theLMGN.likes-gay.men/a6wfz.png)
   - [The horrible blurry scaling on this logo](https://theLMGN.likes-gay.men/j5ain.png)
   - Also, who would use this. Unless you can make a whole new rendering engine that is actually good and make a browser that looks good and actually has features. PEOPLE ARE JUST GOING TO STICK TO FIREFOX/CHROME

I'm also going to PR this and fix everything

**Comment by theLMGN** [comment]
**EDIT:** Turns out the release version, ISN'T the latest.

**Comment by theLMGN** [comment]
@WindowsLogic  you can't just close someones *valid* issue, just because you don't like them.

**Comment by 9002uk** [comment]
This isn't a place to review software.
